fuel_calculator.settings:
  type: config_object
  label: 'Fuel Calculator settings'
  mapping:
    default_distance:
      type: float
      label: 'Default distance'
    default_consumption:
      type: float
      label: 'Default fuel consumption'
    default_price_per_liter:
      type: float
      label: 'Default price per liter'